### ISSUE TITLE
Incremental builds do not work with this crate

### ISSUE THREAD

**Issue by bkase** [Nadrieril/dhall-rust#162]
Thanks for this project!

I've noticed a somewhat significant issue when working with applications that depend on this crate -- incremental builds do not work.

To repro:

```bash
$ mkdir dhall-repro && cd dhall-repro
$ cargo init --application
```

Cargo.toml:

```toml
[package]
name = "dhall-repro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dhall = "0.5.1"
```

src/main.rs:

```rust
extern crate dhall;

fn main() {
    println!("Hello, world!");
}
```

Then, `cargo build` rebuilds `dhall` at every invocation even though the crate is not updated. I have not noticed this behavior with any other crates.

If it is helpful, I am using nightly rust.
